kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    username: justmiles
    password: 
      from_secret: docker_password
    repo: justmiles/dev-sandbox
    tags: latest
    squash: true
    auto_tag: true
    cache_from:
      - "justmiles/dev-sandbox:latest"

- name: semantic-release
  image: hoppr/semantic-release:latest
  environment:
    GH_TOKEN: 
      from_secret: github_token
  commands:
  - semantic-release
