kind: pipeline
type: docker
name: default

steps:
- name: semantic-release
  image: node:16
  commands:
    - npm install -g semantic-release @semantic-release/git @semantic-release/changelog
    - semantic-release
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  when:
    branch:
      - master

- name: docker
  image: plugins/docker
  settings:
    username: justmiles
    password:
      from_secret: docker_password
    repo: justmiles/dev-sandbox
    tags:
      - latest
      - ${DRONE_TAG=latest}
    squash: true
    auto_tag: true
    cache_from:
      - "justmiles/dev-sandbox:latest"
  when:
    event:
      - push
      - tag
