#!/command/with-contenv sh

# Set default userspace
TS_USERSPACE="${TS_USERSPACE:-true}"

[ ! -z "${TS_STATE_DIR}" ]      && ARGS="--statedir=${TS_STATE_DIR} ${ARGS}"
[ ! -z "${TS_STATE}" ]          && ARGS="--state=${TS_STATE} ${ARGS}"
[ "${TS_USERSPACE}" = "true" ]  && ARGS="--tun=userspace-networking ${ARGS}"

tailscaled ${ARGS} 2>&1 | s6-log -bp n3 'p[tailscaled]' 1 /var/log/tailscaled
